---
back:
  image: baoqu/back
  ports:
    - "127.0.0.1:5050:5050"
  volumes:
    - "./baoqu-back:/app"

front:
  image: baoqu/front
  links:
    - back:back
  ports:
    - "127.0.0.1:3449:3449"
  volumes:
    - "./baoqu-front:/app"
